# Joints limits
#
# Sources:
#
#  - Universal Robots e-Series, User Manual, UR5e, Version 5.8
#    https://s3-eu-west-1.amazonaws.com/ur-support-site/69091/99404_UR5e_User_Manual_en_Global.pdf
#  - Support > Articles > UR articles > Max. joint torques
#    https://www.universal-robots.com/articles/ur-articles/max-joint-torques
#    retrieved: 2020-06-16, last modified: 2020-06-09


# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.05
default_acceleration_scaling_factor: 0.05

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

joint_limits:
  arm_shoulder_pan_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 3.14159265359
    max_velocity: 1.57079632679
    min_position: -3.14159265359
    max_acceleration: 3.49
  arm_shoulder_lift_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 3.14159265359
    max_velocity: 1.57079632679
    min_position: -3.14159265359
    max_acceleration: 3.49
  arm_elbow_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 3.14159265359
    max_velocity: 1.57079632679
    min_position: -3.14159265359
    max_acceleration: 3.49
  arm_wrist_1_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 3.14159265359
    max_velocity: 1.57079632679
    min_position: -3.14159265359
    max_acceleration: 3.49
  arm_wrist_2_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 3.14159265359
    max_velocity: 1.57079632679
    min_position: -3.14159265359
    max_acceleration: 3.49
  arm_wrist_3_joint:
    # acceleration limits are not publicly available
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 3.14159265359
    max_velocity: 1.57079632679
    min_position: -3.14159265359
    has_acceleration_limits: true
    max_acceleration: 3.49
