/**:
  ros__parameters:
    # Common servo parameters
    ## Properties of outgoing commands
    command_out_topic: /arm_controller/joint_trajectory  # Topic to publish commands to
    command_out_type: trajectory_msgs/JointTrajectory  # Type of command
    publish_period: 0.034  # 1/Nominal publish rate [seconds]

    ## Properties of incoming commands
    command_in_type: "unitless"  # "unitless"> in the range [-1:1], as if from joystick
    scale:
      # Scale parameters are only used if command_in_type=="unitless"
      linear: 0.4  # Max linear velocity. Unit is [m/s]. Only used for Cartesian commands.
      rotational: 0.8  # Max angular velocity. Unit is [rad/s]. Only used for Cartesian commands.
      joint: 0.5  # Max joint angular/linear velocity. Only used for joint commands on joint_command_in_topic.

    # Incoming Joint State properties
    joint_topic: joint_states
    # Wait this long for incoming joint states (if not present, Servo will not start)
    incoming_command_timeout: 1.0  # Stop servoing if X seconds elapse without a new command

    # MoveIt properties
    robot_link_command_frame: arm_tool0  # The name of the end effector frame
    move_group_name: arm  # The name of the MoveIt move_group
    planning_frame: arm_base_link  # The name of the planning frame (usually base_link)

    ## MoveIt planning
    use_gazebo: false  # Whether the robot is started in a Gazebo simulation environment
    check_collisions: true  # Check collisions?
    collision_check_rate: 10.0  # Rate to check for collisions [Hz]
    collision_check_type: threshold_distance  # Type of collision check
    self_collision_proximity_threshold: 0.01  # Start decelerating when a collision is this far [m]
    scene_collision_proximity_threshold: 0.02  # Start decelerating when a collision is this far [m]

    ## Topic names
    cartesian_command_in_topic: ~/delta_twist_cmds  # Topic for Cartesian twist commands
    joint_command_in_topic: ~/delta_joint_cmds  # Topic for joint angle commands
    robot_description_topic: /robot_description

    ## Smoothing and filtering
    smoother_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

    ## Collision checking
    collision_distance_safety_factor: 1000.0  # Must be >= 1. A large safety factor is recommended.
    min_allowable_collision_distance: 0.01  # Stop servoing if any collision is closer than this [m]

    ## Velocity and acceleration limits
    override_velocity_scaling_factor: 0.0  # Override constant scalar of max joint velocity. 0.0 means use robot limits.

    ## Singularity checking
    lower_singularity_threshold: 17.0  # Start decelerating when the condition number hits this (close to singularity)
    hard_stop_singularity_threshold: 30.0  # Stop when the condition number hits this
    leaving_singularity_threshold_multiplier: 2.0  # Multiply the hard stop limit by this when leaving singularity

    ## Algorithm settings
    num_outgoing_halt_msgs_to_publish: 4  # Publish N halt messages on startup
