# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 0.5  # Allow 0.5 seconds to settle after trajectory end
      arm_shoulder_pan_joint:
        goal: 0.01  # 0.01 radians = ~0.57 degrees
      arm_shoulder_lift_joint:
        goal: 0.01
      arm_elbow_joint:
        goal: 0.01
      arm_wrist_1_joint:
        goal: 0.01
      arm_wrist_2_joint:
        goal: 0.01
      arm_wrist_3_joint:
        goal: 0.01
gripper_controller:
  ros__parameters:
    joint: finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 0.5
      finger_joint:
        goal: 0.01